return {

    diagnostic_icons = {
        Error = " ",
        Warn = " ",
        Hint = " ",
        Info = " ",
    },
    cmp = {
        Folder = "  (Folder)",
        File = "  (File)",
        Package = "  (Package)",
        Module = "  (Module)",
        Namespace = "  (Namespace)",
        Interface = "  (Interface)",
        Constructor = "   (Constructor)",
        Enum = "  (Enum)",
        EnumMember = "  (EnumMember)",
        Class = "  (Class)",
        Method = "  (Method)",
        Function = "  (Function)",
        Property = "  (Property)",
        Field = "  (Field)",
        Constant = "  (Constant)",
        Variable = "  (Variable)",
        String = "  (String)",
        Number = "  (Number)",
        Boolean = " ◩ (Boolean)",
        Array = "  (Array)",
        Object = "  (Object)",
        Key = "  (Key)",
        Null = " ﳠ (Null)",
        Struct = "  (Struct)",
        Event = "  (Event)",
        Operator = "  (Operator)",
        TypeParameter = "  (TypeParameter)",
        Text = "  (Text) ",
        Unit = "  (Unit)",
        Value = "  (Value)",
        Keyword = "  (Keyword)",
        Snippet = "  (Snippet)",
        Color = "  (Color)",
        Reference = "  (Reference)",
    },
    lsp = {
        File = " ",
        Module = " ",
        Namespace = " ",
        Package = " ",
        Class = " ",
        Method = " ",
        Property = " ",
        Field = " ",
        Constructor = " ",
        Enum = " ",
        Interface = " ",
        Function = " ",
        Variable = " ",
        Constant = " ",
        String = " ",
        Number = " ",
        Boolean = "◩ ",
        Array = " ",
        Object = " ",
        Null = "ﳠ ",
        Key = " ",
        EnumMember = " ",
        Struct = " ",
        Event = " ",
        Operator = " ",
        TypeParameter = " ",
    },
    outline = {
        File = { icon = "", hl = "@directory" },
        Module = { icon = "", hl = "@include" },
        Namespace = { icon = "", hl = "@namespace" },
        Package = { icon = "", hl = "@include" },
        Class = { icon = "", hl = "@structure" },
        Method = { icon = "", hl = "@method" },
        Property = { icon = "", hl = "@property" },
        Field = { icon = " ", hl = "@field" },
        Constructor = { icon = "", hl = "@constructor" },
        Enum = { icon = "", hl = "@field" },
        Interface = { icon = "", hl = "@type" },
        Function = { icon = "", hl = "@function" },
        Variable = { icon = "", hl = "@variable" },
        Constant = { icon = "", hl = "@constant" },
        String = { icon = "", hl = "@string" },
        Number = { icon = "", hl = "@number" },
        Boolean = { icon = "◩", hl = "@boolean" },
        Array = { icon = "", hl = "@field" },
        Object = { icon = "", hl = "@type" },
        Key = { icon = "", hl = "@keyword" },
        Null = { icon = "ﳠ", hl = "@comment" },
        EnumMember = { icon = "", hl = "@field" },
        Struct = { icon = "", hl = "@structure" },
        Event = { icon = "", hl = "@keyword" },
        Operator = { icon = "", hl = "@operator" },
        TypeParameter = { icon = "", hl = "@type" },
    },
    hl = {
        File = "Directory",
        Module = "@include",
        Namespace = "@namespace",
        Package = "@include",
        Class = "@structure",
        Method = "@method",
        Property = "@property",
        Field = "@field",
        Constructor = "@constructor",
        Enum = "@field",
        Interface = "@type",
        Function = "@function",
        Variable = "@variable",
        Constant = "@constant",
        String = "@string",
        Number = "@number",
        Boolean = "@boolean",
        Array = "@field",
        Object = "@type",
        Key = "@keyword",
        Null = "@comment",
        EnumMember = "@field",
        Struct = "@structure",
        Event = "@keyword",
        Operator = "@operator",
        TypeParameter = "@type",
    },
}
