local global = require("rolfst.global")

vim.opt.number = true
vim.opt.relativenumber = true

vim.opt.shiftwidth = 4
vim.opt.softtabstop = 4
vim.opt.expandtab = true
vim.opt.tabstop = 4
vim.opt.smarttab = true

vim.opt.smartindent = true
vim.opt.autoindent = true

vim.opt.wrap = false

vim.opt.swapfile = false
vim.opt.backup = false
vim.opt.writebackup = false
vim.opt.backupdir = global.cache_path .. "/backup/"
vim.opt.undofile = true
vim.opt.undodir = global.cache_path .. "/undo/"

vim.opt.cursorline = true
vim.opt.hlsearch = false
vim.opt.incsearch = true
vim.opt.guicursor = ""
vim.opt.termguicolors = true
vim.opt.colorcolumn = "100"
vim.opt.signcolumn = "yes"

vim.opt.backspace = "indent,eol,start"
vim.opt.backupskip = "/tmp/*,$TMPDIR/*,$TMP/*,$TEMP/*,*/shm/*,/private/var/*,.vault.vim"
vim.opt.breakat = [[\ \	;:,!?]]
vim.opt.breakindentopt = "shift:2,min:20"
vim.opt.clipboard = "unnamedplus"
vim.opt.cmdheight = 2
vim.opt.cmdwinheight = 5
vim.opt.completeopt = "menu,menuone,noselect"
vim.opt.complete = ".,w,b,k"
vim.opt.concealcursor = "nc"
vim.opt.conceallevel = 2
vim.opt.diffopt = "filler,iwhite,internal,algorithm:patience"
vim.opt.directory = global.cache_path .. "/swag/"
vim.opt.display = "lastline"
vim.opt.encoding = "utf-8"
vim.opt.equalalways = false
vim.opt.errorbells = true
vim.opt.fileformats = "unix,mac,dos"
vim.opt.fillchars = "eob: "
vim.opt.foldenable = true
vim.opt.foldexpr = "nvim_treesitter#foldexpr()"
vim.opt.foldlevelstart = 99
vim.opt.foldmethod = "expr"
vim.opt.formatoptions = "1jcroql"
vim.opt.grepformat = "%f:%l:%c:%m"
vim.opt.grepprg = "rg --hidden --vimgrep --smart-case --"
vim.opt.helpheight = 12
vim.opt.hidden = true
vim.opt.history = 2000
vim.opt.ignorecase = true
vim.opt.inccommand = "nosplit"
vim.opt.infercase = true
vim.opt.jumpoptions = "stack"
vim.opt.laststatus = 3
vim.opt.linebreak = true
vim.opt.listchars = "tab:  ,nbsp: ,trail: ,space: ,extends:→,precedes:←"
vim.opt.list = true
vim.opt.magic = true
vim.opt.mouse = "nv"
vim.opt.previewheight = 12
vim.opt.pumblend = 0
vim.opt.pumheight = 15
vim.opt.redrawtime = 1500
vim.opt.ruler = false
vim.opt.scrolloff = 8
vim.opt.sessionoptions = "curdir,help,tabpages,winsize"
vim.opt.shada = "!,'300,<50,@100,s10,h"
vim.opt.shiftround = true
vim.opt.shortmess = "aoOTIcF"
vim.opt.showbreak = "↳  "
vim.opt.showcmd = false
vim.opt.showmode = false
vim.opt.showtabline = 1
vim.opt.sidescrolloff = 5
vim.opt.smartcase = true
vim.opt.splitbelow = true
vim.opt.splitright = true
vim.opt.startofline = false
-- vim.opt.switchbuf = "useopen"
vim.opt.synmaxcol = 2500
vim.opt.textwidth = 120
vim.opt.timeoutlen = 500
vim.opt.timeout = true
vim.opt.ttimeoutlen = 10
vim.opt.ttimeout = true
vim.opt.updatetime = 100
vim.opt.viewdir = global.cache_path .. "/view/"
vim.opt.viewoptions = "folds,cursor,curdir,slash,unix"
vim.opt.virtualedit = "block"
vim.opt.visualbell = true
vim.opt.whichwrap = "h,l,<,>,[,],~"
vim.opt.wildignore =
".git,.hg,.svn,*.pyc,*.o,*.out,*.jpg,*.jpeg,*.png,*.gif,*.zip,**/tmp/**,*.DS_Store,**/node_modules/**,**/bower_modules/**"
vim.opt.wildignorecase = true
vim.opt.winblend = 0
vim.opt.winminwidth = 10
vim.opt.winwidth = 30
vim.opt.wrapscan = true
